name: Build Mobile Binary

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Download Go Dependencies
      run: |
        go mod tidy

    - name: Build Android ARM64 Executable
      run: |
        CGO_ENABLED=0 GOOS=android GOARCH=arm64 go build -mod=mod -o recovery-android-arm64 ./recovery_tool

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v4
      with:
        name: recovery-android-arm64
        path: recovery-android-arm64
        if-no-files-found: error
