name: Build Android APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Set up Java/JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        gomobile init

    - name: Build Binary / Package
      run: |
        cd recovery_tool
        GOOS=android GOARCH=arm64 go build -o recovery-android-arm64

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: recovery-android-binary
        path: recovery_tool/recovery-android-arm64
